apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications
    repoURL: https://github.com/developer-guy/bring-gitops-to-your-openfaas-functions-with-argocd.git
  syncPolicy:
    automated:
      selfHeal: true
